//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecipeMvc2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ingredient
    {
        public Nullable<int> RecipeId { get; set; }
        public string Ingredient1 { get; set; }
        public int IngredientId { get; set; }
    
        public virtual Recipe Recipe { get; set; }
    }
}
