//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecipeMvc2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrepTime
    {
        public Nullable<int> PrepTime1 { get; set; }
        public int PrepTimeId { get; set; }
    
        public virtual CookingTime CookingTime { get; set; }
        public virtual Step Step { get; set; }
    }
}
