//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecipeMvc2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recipe
    {
        public int RecipeId { get; set; }
        public string RecipeName { get; set; }
        public System.TimeSpan CookingTime { get; set; }
        public Nullable<int> Serves { get; set; }
        public string Ingredient { get; set; }
        public Nullable<int> CookingTimeId { get; set; }
        public Nullable<int> ServesId { get; set; }
        public Nullable<int> IngredientId { get; set; }
    
        public virtual CookingTime CookingTime1 { get; set; }
        public virtual Ingredient Ingredient1 { get; set; }
        public virtual Serve Serve { get; set; }
    }
}
