//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecipeMvc2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Step
    {
        public int StepsId { get; set; }
        public string Steps { get; set; }
    
        public virtual PrepTime PrepTime { get; set; }
    }
}
