USE [master]
GO

/****** Object:  Database [Recipe]    Script Date: 7/30/2014 1:07:54 PM ******/
CREATE DATABASE [Recipe]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Recipe', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\Recipe.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Recipe_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\Recipe_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [Recipe] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Recipe].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Recipe] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Recipe] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Recipe] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Recipe] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Recipe] SET ARITHABORT OFF 
GO

ALTER DATABASE [Recipe] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Recipe] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Recipe] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Recipe] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Recipe] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Recipe] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Recipe] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Recipe] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Recipe] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Recipe] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Recipe] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Recipe] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Recipe] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Recipe] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Recipe] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Recipe] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Recipe] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Recipe] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Recipe] SET  MULTI_USER 
GO

ALTER DATABASE [Recipe] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Recipe] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Recipe] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Recipe] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [Recipe] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Recipe] SET  READ_WRITE 
GO

